[package]
name = "jaypty"
version = "0.0.1"
description = "cross platform pty interface. currently in WIP so as of now (5/10/26), it only supports Windows 10 + Windows 11"
license = "MIT"
edition = "2024"


[dependencies]
jaypty_core = {path = "../core", version = "0.0.1", }
polling = "3.11.0"


[target.'cfg(windows)'.dependencies]
ptywin = {version = "0.0.1", path = "../ptywin"}


[target.'cfg(unix)'.dependencies]
unixpty = {path = "../unixpty"}

[features]
default = []
win = []
unix = []
