[package]
name = "ptywin"
version = "0.0.1"
description = "interface between contpy implementing the PseudoTerminal trait found in jaypty"
license = "MIT"
edition = "2024"


[dependencies]
log = "0.4.29"
mio = {version = "1.2.0", features = ["os-poll", "os-ext"]}
miow = "0.6.1"
piper = "0.2.5"
polling = "3.11.0"
thiserror = "2.0.18"
jaypty_core = {version = "0.0.1", path = "../core"}
jaysync = {version = "0.0.1", path = "../jaysync"}
env_logger = "0.11.10"
winpipe = {verion = "0.0.1", path = "../winpipe", features = ["polling"]}

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.59.0", features = [
    "Win32_System_Console",
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_LibraryLoader",
    "Win32_System_Threading",
    "Win32_System_WindowsProgramming",
]}
